# set base image (host OS)
FROM python:3.8

ENV HOME /root

# set the working directory in the container
WORKDIR /root

COPY . .
# install dependencies

#RUN pip3 install -r requirements.txt
# copy the content of the local src directory to the working directory

EXPOSE 8000

# command to run on container start
CMD ["python3", "server.py"]